apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv-fe-data
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
