apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv-fe-data
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.111.25 #192.168.111.29 DEV
    path: "/var/nfs/general"
    readOnly: no
  persistentVolumeReclaimPolicy: Retain
