apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa-pac-method-ws-short 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: fe-pac-method-ws-short 
  minReplicas: 1 
  maxReplicas: 3 
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 50 
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 100           
