apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa-mq-listener 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: fe-mq-listener 
  minReplicas: 25 
  maxReplicas: 35
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 50 
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 100      
