apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-mq-listener
  namespace: default
spec:
  selector:
    matchLabels:
      app: fe-mq-listener
  replicas: 1
  template:
    metadata:
      labels:
        app: fe-mq-listener
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-nfs-pv-fe-data
      containers:
        - image: jomimart13/fe-listener-data:latest
          imagePullPolicy: Always
          name: fe-mq-listener
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"          
          volumeMounts:
            - name: data
              mountPath: /nfs/general
          #command: ["/bin/sh"]
          #args: ["-c", "while true; do date >> /var/nfs/general/filepu.txt; sleep 5; done"]
          ports:
            - containerPort: 8080
          env:
            - name: spring.rabbitmq.host
              value: rabbitmq.default.svc.cluster.local
            - name: spring.rabbitmq.username
              value: user
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: k8s.basepath
              value: /
            - name: k8s.wspubliser
              value: http://fe-mq-publisher-service.default.svc.cluster.local/publish/fe
            - name: k8s.wspubliserdb
              value: http://fe-mq-publisher-service.default.svc.cluster.local/publish/db
            - name: k8s.wsupdateinvoice
              value: http://fe-crud-service.default.svc.cluster.local/invoice/patch
            - name: flagstatsIngest
              value: "true"
            - name: k8s.wsstatsIngest
              value: http://fe-elastic-crud-service.default.svc.cluster.local/stats/ingest              
            - name: logging.file.name
              value: trace.log
            - name: queueEnabledStatus
              value: 500,501,502,503,504
            - name: aludra.base
              value: https://qa-apim.aludra.cloud              
            - name: aludra.endpoint.mdl16.fe
              value: /mdl16/XMLfeRecfeDGI
            - name: aludra.apikey
              value: FHEpi3JahRB23g3Dn1D11KQQN4OV8yO1IgawjV/ggEeK2r3NT4bRwwzDe1HSJ1IksfyWo7Q+DC8OuKVuOlarbvhuenq7hXq8lp+k9/H6QCZrgKd1pgYE+068sAGmnLL59/cxLkYCwsW6ggpEWeSnRZDGgj62pBja9RDaMDkM37v5PIEBh2rkU6IyywVA/3fjvyIFfwRTwMQ4bQfGooDuHVJidd+Nn0SFjF1rAPhfz7qQjSMCc1U6I0ZlOlJhMaPg6xuaduS68fBSitiFqWf4d8LIxhqT/lJrDhRMSiFDVC5pq+G6BSHyCO6qFRwQ0DDjSH8ZjrnCASRP7UtT811QJQ4o+rGjdACaDyZUUqSLs4s=
            - name: aludra.subscriptionKey
              value: f718d6d8af9848008b8f6a6f516cb7ba
            - name: aludra.company
              value: HYPE              