apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa-ingest-data 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: fe-ingest-data 
  minReplicas: 4 
  maxReplicas: 6 
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 50 
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 100           
