apiVersion: v1
kind: Service
metadata:
  name: rabbitclient
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
#  type: NodePort
  selector:
    app: rabbitclient
