apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa-mq-listener 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: fe-mq-listener 
  minReplicas: 1 
  maxReplicas: 5 
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 50 
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Max       
