apiVersion: v1
kind: Service
metadata:
  name: fe-mq-listener-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: fe-mq-listener
