apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-pac-method-ws-long
  namespace: default
spec:
  selector:
    matchLabels:
      app: fe-pac-method-ws-long
  replicas: 1
  template:
    metadata:
      labels:
        app: fe-pac-method-ws-long
    spec:
      containers:
      - image: soportehypernovalabs/fe-pac-as-ws:longqr-qa-version
        imagePullPolicy: IfNotPresent
        name: fe-pac-method-ws-long
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"        
        ports:
        - containerPort: 8080
