apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-invoice-dgi
  namespace: default
spec:
  selector:
    matchLabels:
      app: fe-invoice-dgi
  replicas: 1
  template:
    metadata:
      labels:
        app: fe-invoice-dgi
    spec:
      containers:
        - image: soportehypernovalabs/fe-invoice-dgi:latest
          imagePullPolicy: Always
          name: fe-invoice-dgi
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"          
          ports:
            - containerPort: 8080
          env:
            - name: aludra.base
              value: https://apim.aludra.cloud              
            - name: aludra.endpoint.mdl16.fe
              value: /mdl16/XMLfeRecfeDGI
            - name: aludra.apikey
              value: J8Mk6RRusbbu+aHJG1zdR+fAaRE6o373fYPqepP0YKcLXkFNUzSfTTeKMKAQSKfjLHKnc6OI3z111HJD3drFUvW1nPOrmlD0q3UCl1KnH+2QtbiEr3Wil/GRoQjexeHmFULEmzzDw23mIg/022VwNwManVIFjRR+5pzH5YjnDDpt2/6oqUT5xhbltwPNUAFfILad8ywERL6ZzC7FYQV+mqfAoMgWPxwPPZayRwRg4Y8WROiD3+GEMgVWTSKGMJpbxmyjNuMtsPgIUGPGaKZdlhfUoJZ7/FHeC3PfzECZy2wpN7R7Bdd1QmEmc35xkXNVvy0qpMVvstY1UiPBaSnGjuDPMwSSPZ2+YEJar15er2E=
            - name: aludra.subscriptionKey
              value: 286e8fb385cb48769b3b31ff5bb1bcf7
            - name: aludra.company
              value: REY1              