apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-mq-publisher
  namespace: default
spec:
  selector:
    matchLabels:
      app: fe-mq-publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: fe-mq-publisher
    spec:
      containers:
      - image: soportehypernovalabs/fe-mq-publisher:latest
        imagePullPolicy: IfNotPresent
        name: fe-mq-publisher
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"          
        ports:
        - containerPort: 8080
        env:
            - name: spring.rabbitmq.host
              value: rabbitmq.default.svc.cluster.local
            - name: spring.rabbitmq.username
              value: user
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: logging.file.name
              value: /nfs/general/trace.log                 
            - name: exchange.name
              value: delay_exchange_queue             
            - name: routing.name
              value: routing_queue
            - name: queue.rejected
              value: queue.fe.input.rejected              
            - name: queue.db.name
              value: queue.db    
      imagePullSecrets:
      - name: azrcrsecret   