apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-mq-listener
  namespace: default
spec:
  selector:
    matchLabels:
      app: fe-mq-listener
  replicas: 1
  template:
    metadata:
      labels:
        app: fe-mq-listener
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-nfs-pv-fe-data
      containers:
        - image: soportehypernovalabs/fe-listener-data:latest
          imagePullPolicy: Always
          name: fe-mq-listener
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"          
          volumeMounts:
            - name: data
              mountPath: /nfs/general
          #command: ["/bin/sh"]
          #args: ["-c", "while true; do date >> /var/nfs/general/filepu.txt; sleep 5; done"]
          ports:
            - containerPort: 8080
          env:
            - name: spring.rabbitmq.host
              value: rabbitmq.default.svc.cluster.local
            - name: spring.rabbitmq.username
              value: user
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: k8s.basepath
              value: /
            - name: k8s.wspubliser
              value: http://fe-mq-publisher-service.default.svc.cluster.local/publish/fe
            - name: k8s.wspubliserdb
              value: http://fe-mq-publisher-service.default.svc.cluster.local/publish/db
            - name: k8s.wsupdateinvoice
              value: http://fe-crud-service.default.svc.cluster.local/invoice/patch
            - name: flagstatsIngest
              value: "true"
            - name: k8s.wsstatsIngest
              value: http://fe-elastic-crud-service.default.svc.cluster.local/stats/ingest              
            - name: logging.file.name
              value: trace.log
            - name: queueEnabledStatus
              value: 500,501,502,503,504
            - name: aludra.base
              value: https://qa-apim.aludra.cloud              
            - name: aludra.endpoint.mdl16.fe
              value: /mdl16/XMLfeRecfeDGI
            - name: aludra.apikey
              value: vqW+I++PyUAsXe90TBKpLQVw9sg5v0SFzU3SYGuuQmYkErzSffACULX+THENtNY7l/cGatWlfixwLfM6sW6MuojrQUgXaTuofaStEcPhya/Q4MrphGSyHySIoo0W+fKi6puW8NfYw+Q1hnwEJLY9B276++cKZVDM8Gv688KwYbxw6gpg4h36VXg1sbqz5CzAdT426w8k51QlpM8vuqYIEJMIgPhMn4xxOsc9Iz7FfIEkD2j9kCZNFn/0/CY41fwVefMyO++2IisN96eVNNjgZBgdy5P0aFqEgbfBUezSDXDJRCv1zsiJku12V736e+j2mffjhQ7ASwZ+fFtD1QgJ9Yz9m6ErcRALI9Tj6kcdaNo=
            - name: aludra.subscriptionKey
              value: f718d6d8af9848008b8f6a6f516cb7ba
            - name: aludra.company
              value: HYPE              